### ISSUE TITLE
Problem running demo.py 

### ISSUE THREAD

**Issue by tabiva** [uvc-ingenieure/pyveloedi#1]
Hi, 
I get an error while running demo.py, with valid credentials. This is the stacktrace:

> Traceback (most recent call last):
>   File "demo.py", line 49, in <module>
>     main()
>   File "demo.py", line 18, in main
>     product_ids = EDIProduct.search(['glocke'], offset=0, limit=10, count=False)
>   File "build/bdist.linux-x86_64/egg/pyveloedi/veloconnect.py", line 530, in search
>   File "build/bdist.linux-x86_64/egg/pyveloedi/veloconnect.py", line 356, in execute
>   File "build/bdist.linux-x86_64/egg/pyveloedi/veloconnect.py", line 171, in dispatch_request
> pyveloedi.veloconnect.VeloConnectException: 'Request not supported. (Code: 404)'

Any ideas? 
Thank you!

**Comment by mholtzberg** [comment]
Seems like the server does not support that specific request. We use that code in production so it should actually work.
